
export const FAILURE = 'FAILURE';

export const PRODUCT_TITLES_SUCCESS = 'PRODUCT_TITLES_SUCCESS';
export const PRODUCT_TITLES_REQUEST = 'PRODUCT_TITLES_REQUEST';
export const PRODUCT_TITLES_RESET = 'PRODUCT_TITLES_RESET';

export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_RESET = 'PRODUCT_DETAIL_RESET';

export const SELLER_DETAIL_SUCCESS = 'SELLER_DETAIL_SUCCESS';
export const SELLER_DETAIL_REQUEST = 'SELLER_DETAIL_REQUEST';
export const SELLER_DETAIL_RESET = 'SELLER_DETAIL_RESET';

export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORY_RESET = 'CATEGORY_RESET';

export const TAGLINE_SUCCESS = 'TAGLINE_SUCCESS';
export const TAGLINE_REQUEST = 'TAGLINE_REQUEST';
export const TAGLINE_RESET = 'TAGLINE_RESET';

export const SLIDE_SUCCESS = 'SLIDE_SUCCESS';
export const SLIDE_REQUEST = 'SLIDE_REQUEST';
export const SLIDE_RESET = 'SLIDE_RESET';

export const QUERY_SUCCESS = 'QUERY_SUCCESS';
export const QUERY_REQUEST = 'QUERY_REQUEST';
export const QUERY_RESET = 'QUERY_RESET';

export const HIGH_RES_SUCCESS = 'HIGH_RES_SUCCESS';
export const HIGH_RES_REQUEST = 'HIGH_RES_REQUEST';
export const HIGH_RES_RESET = 'HIGH_RES_RESET';

export const LOW_RES_SUCCESS = 'LOW_RES_SUCCESS';
export const LOW_RES_REQUEST = 'LOW_RES_REQUEST';
export const LOW_RES_RESET = 'LOW_RES_RESET';