export const FAILURE = 'FAILURE';

export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST';
export const QUESTIONS_RESET = 'QUESTIONS_RESET';

export const QUESTIONS_RATING_SUCCESS = 'QUESTIONS_RATING_SUCCESS';
export const QUESTIONS_RATING_REQUEST = 'QUESTIONS_RATING_REQUEST';
export const QUESTIONS_RATING_RESET = 'QUESTIONS_RATING_RESET';