export const FAILURE = 'FAILURE';

export const REVIEWS_SUCCESS = 'REVIEWS_SUCCESS';
export const REVIEWS_REQUEST = 'REVIEWS_REQUEST';
export const REVIEWS_RESET = 'REVIEWS_RESET';

export const REVIEWS_IMGS_SUCCESS = 'REVIEWS_IMGS_SUCCESS';
export const REVIEWS_IMGS_REQUEST = 'REVIEWS_IMGS_REQUEST';
export const REVIEWS_IMGS_RESET = 'REVIEWS_IMGS_RESET';

export const USER_IMGS_SUCCESS = 'USER_IMGS_SUCCESS';
export const USER_IMGS_REQUEST = 'USER_IMGS_REQUEST';
export const USER_IMGS_RESET = 'USER_IMGS_RESET';

export const USER_REVIEW_SUCCESS = 'USER_REVIEW_SUCCESS';
export const USER_REVIEW_REQUEST = 'USER_REVIEW_REQUEST';
export const USER_REVIEW_RESET = 'USER_REVIEW_RESET';

export const UPDATE_RATING_SUCCESS = 'UPDATE_RATING_SUCCESS';
export const UPDATE_RATING_REQUEST = 'UPDATE_RATING_REQUEST';
export const UPDATE_RATING_RESET = 'UPDATE_RATING_RESET';

export const UPLOAD_IMAGES_REQUEST = 'UPLOAD_IMAGES_REQUEST';
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS';
export const UPLOAD_IMAGES_RESET = 'UPLOAD_IMAGES_RESET';

export const DELETE_IMAGES_REQUEST = 'DELETE_IMAGES_REQUEST';
export const DELETE_IMAGES_SUCCESS = 'DELETE_IMAGES_SUCCESS';

export const ADD_UPDATE_USER_REVIEW_SUCCESS = 'ADD_UPDATE_USER_REVIEW_SUCCESS';
export const ADD_UPDATE_USER_REVIEW_REQUEST = 'ADD_UPDATE_USER_REVIEW_REQUEST';
export const ADD_UPDATE_USER_REVIEW_RESET = 'ADD_UPDATE_USER_REVIEW_RESET';

export const ADD_UPDATE_USER_IMGS_SUCCESS = 'ADD_UPDATE_USER_IMGS_SUCCESS';
export const ADD_UPDATE_USER_IMGS_REQUEST = 'ADD_UPDATE_USER_IMGS_REQUEST';
export const ADD_UPDATE_USER_IMGS_RESET = 'ADD_UPDATE_USER_IMGS_RESET';