export const FAILURE = 'FAILURE'

export const LOGOUT = 'LOGOUT'

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'

export const DELETE_REQUEST = 'DELETE_REQUEST'
export const DELETE_SUCCESS = 'DELETE_SUCCESS'

export const REMOVE_FROM_CART_REQUEST = 'REMOVE_FROM_CART_REQUEST'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'

export const ADD_TO_MY_ORDERS_REQUEST = 'ADD_TO_MY_ORDERS_REQUEST'
export const ADD_TO_MY_ORDERS_SUCCESS = 'ADD_TO_MY_ORDERS_SUCCESS'

export const MY_ORDERS_REQUEST = 'MY_ORDERS_REQUEST'
export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS'
export const MY_ORDERS_RESET = 'MY_ORDERS_RESET'

export const USER_REVIEW_FEEDBACK_REQUEST = 'USER_REVIEW_FEEDBACK_REQUEST'
export const USER_REVIEW_FEEDBACK_SUCCESS = 'USER_REVIEW_FEEDBACK_SUCCESS'

export const USER_QA_FEEDBACK_REQUEST = 'USER_QA_FEEDBACK_REQUEST'
export const USER_QA_FEEDBACK_SUCCESS = 'USER_QA_FEEDBACK_SUCCESS'